version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      mysql-container:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/todolistdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    restart: on-failure
    networks:
      - backend-net

  mysql-container:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todolistdb
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin" ]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-net

volumes:
  db_data:

networks:
      backend-net:
